discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from . import views

# Syntax
# path (route, view, name)

app_name = 'todolist'

urlpatterns = [
	path('', views.index, name='index'),
	path('eh', views.yeet, name='yeet'),
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
	path('events/<int:event_id>/', views.event, name='viewevent'),
	path('events/<int:event_id>/edit', views.update_event, name='update_event'),
	path('events/<int:event_id>/delete', views.delete_event, name='delete_event'),

	path('register', views.register, name='register'),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('add_event', views.add_event, name="add_event"),

]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class events(models.Model):
	event_name = models.CharField(max_length=50)
	Description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label="Description",max_length=200)

class UpdateTaskForm(forms.Form):

	# If field are optional, using the "Model.save()" method will not work
	# Using the option "required-False" will allow the field to be option when updating a record
	# task_name = forms.CharField(label='Task Name', max_length=50, requires=False)
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=50)
	Description = forms.CharField(label="Description",max_length=200)

class UpdateEventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=50)
	Description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

#from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone


from .models import ToDoItem, events
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, AddEventForm, UpdateEventForm

# Create your views here.
def index(request):
	# todoitem_list = ToDoItem.objects.all()
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	event_list = events.objects.filter(user_id=request.user.id)
	context={
		'event_list' : event_list,
		'todoitem_list' : todoitem_list,
		'user' : request.user
	}
	return render(request, "todolist/index.html", context)



	# todoitem_list = ToDoItem.objects.all()
	# template = loader.get_template("todolist/index.html")
	# context={
	# 	'todoitem_list' : todoitem_list
	# }
	# return HttpResponse(template.render(context, request))


	# todoitem_list = ToDoItem.objects.all()
	# output = ', '.join([todoitem.task_name for todoitem in todoitem_list])
	# return HttpResponse(output)

	# return HttpResponse("Hello from CEBU?")

def yeet(request):
	return HttpResponse("Eh?!")

def todoitem(request, todoitem_id):
	
	# todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	# return render(request, "todolist/todoitem.html", todoitem)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))
	# response = "You are viewing the details of %s"
	# return HttpResponse(response % todoitem_id)

def event(request, event_id):
	print('event function called')
	event = get_object_or_404(events, pk=event_id)
	return render(request, "todolist/event.html", model_to_dict(event))


def register(request):
	users = User.objects.all()
	is_user_registered = False
	context ={
	"is_user_registered": is_user_registered	
	}
	
	for indiv_user in users:
		if indiv_user.username == "johndoe":
			is_user_registered = True
			break

	if is_user_registered == False:

		user = User()
		user.username = "johndoe"
		user.first_name = "John"
		user.last_name = "Doe"
		user.email = "john@mail.com"
		# user.password = "john1234"
		# The set_password method is used tp ensure that the password is hashed
		user.set_password("john1234")
		user.is_staff = False
		user.is_active = True
		user.save()
		context = {
			"first_name": user.first_name, 
			"last_name": user.last_name
		}

	return render(request, "todolist/register.html", context)


def change_password(request):
	is_user_authenticated = False

	user = authenticate(username="johndoe",password="john1234")
	print(user)

	if user is not  None:
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		# user.set_password("johndoe1")
		# user.save()
		is_user_authenticated = True

	context = {
		"is_user_authenticated" : is_user_authenticated
	}

	return render(request, "todolist/change_password.html",context)

def login_view(request):

    context = {}

    # If this is a POST request we need to process the form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request 
        form = LoginForm(request.POST)

        # Check whether the data is valid
        # Runs validation routines for all the form fields and returns True and places the forms's data in the "cleaned_data" attribute
        if form.is_valid() == False:

            # Returns a blank login form
            form = LoginForm()

        else:

            # Retrieves the information from the form
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            context = {
                "username": username,
                "password": password
            }

            if user is not None:
                # Saves the user's ID in the session using Django's session framework
                login(request, user)
                return redirect("todolist:index")
            else:
                # Provides context with error to conditionally render the error message
                context = {
                    "error": True
                }

    return render(request, "todolist/login.html", context)


def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):
	context = {}

	if request.method == 'POST':

		form = AddTaskForm(request.POST)

		if form.is_valid() == False:

			form = AddTaskForm()

		else:

			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			# Checks the da tabase if a task already exists
			# By default the "filter" method searches for records that are case insesitive
			duplicates = ToDoItem.objects.filter(task_name=task_name)

			# if todoitem does not contain any duplicates
			if not duplicates:

				# Creates an object based on the "ToDoItem" model and saves the record in the database
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}

	if request.method == 'POST':

		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:

			form = UpdateTaskForm()

		else:

			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:

				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

def delete_event(request, event_id):

	event = events.objects.filter(pk=event_id).delete()
	return redirect("todolist:index")

def update_event(request, event_id):

	event = events.objects.filter(pk=event_id)

	context = {
		"user": request.user,
		"event_id": event_id,
		"event_name": event[0].event_name,
		"Description": event[0].Description,
		"status": event[0].status
	}

	if request.method == 'POST':

		form = UpdateEventForm(request.POST)

		if form.is_valid() == False:

			form = UpdateEventForm()

		else:

			event_name = form.cleaned_data['event_name']
			Description = form.cleaned_data['Description']
			status = form.cleaned_data['status']

			if event:

				event[0].event_name = event_name
				event[0].Description = Description
				event[0].status = status

				event[0].save()
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/update_event.html", context)

def add_event(request):
	context = {}

	if request.method == 'POST':

		form = AddEventForm(request.POST)

		if form.is_valid() == False:

			form = AddEventForm()

		else:

			event_name = form.cleaned_data['event_name']
			Description = form.cleaned_data['Description']

			duplicates = events.objects.filter(event_name=event_name)

			if not duplicates:
				current_user = request.user
				events.objects.create(event_name=event_name, Description=Description, user_id=current_user.id)
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/add_event.html", context)

todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}

	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add An Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate Event found</p>
				{% endif %}
				<form action="{% url 'todolist:add_event' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="event_name">Event Name: </label>
					<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
				</div>
				
				<div class="mb-3">
					<label for="Description">Description: </label>
					<textarea class="form-control" name="Description" value="{{ Description }}" required></textarea>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Event">
				</div>
				
			</form>
			</div>
		</div>
	</div>
{% endblock %}

todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}

	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
				</div>
				
				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" name="description" value="{{ description }}" required></textarea>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Task">
				</div>
				
			</form>
			</div>
		</div>
	</div>
{% endblock %}

todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct.</p>

{% else %}
	<h1>User Password Successfully Updated</h1>
	<p>The password has been successfully updated</p>

{% endif %}

todolist/templates/todolist/event.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{event_name}}</h1>
	<h3>Description</h3>
	<p>{{Description}}</p>
	<h3>Status</h3>
	<p>{{status}}</p>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href="{% url 'todolist:update_event' id %}" class="text-light text-decoration-none">Edit event</a>
	</button>

	<button class="btn btn-danger mx-1 text-decoration-none"><a href="{% url 'todolist:delete_event' id %}" class="text-light text-decoration-none">Delete event</a>
	</button>

	<button class="btn btn-warning mx-1 text-decoration-none"><a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To events</a>
	</button>

</div>

{% endblock %}

todolist/templates/todolist/index.html
{% extends 'base.html' %}

<!-- Provides the title of the page to be provided in the template -->
<!-- This should correspond with the block name provided in the base.html file -->
{% block title %}Home{% endblock %}

<!-- Provides the content of the page to be provided in the template -->
<!-- This should correspond with the block name provided in the base.html file -->
{% block content %}
	{% if todoitem_list and user.is_anonymous == False %}
		<h1 class = "text-center my -3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<div class ="container">
			<div = class ="row">
				<h3 class="text-center mb-3"> My Tasks</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
					{% for todoitem in todoitem_list %}
						<li class="list-group-item">
							<a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
								{{todoitem.task_name}}
							</a>
						</li>
					{% endfor %}
				</ul>
			</div>
	</div>

	<div class ="container">
			<div = class ="row">
				<h3 class="text-center mb-3"> My Events</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
					{% for event in event_list %}
						<li class="list-group-item">
							<a href="{% url 'todolist:viewevent' event.id %}" class="text-decoration-none">
								{{event.event_name}}
							</a>
						</li>
					{% endfor %}
				</ul>
			</div>
	</div>
	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="login">here</a></p>
	{% else %}
		<p>No tasks have been created.</p>
	{% endif %}
{% endblock %}

todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col 6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and password</p>
			{% endif %}
			<form action="{% url 'todolist:login' %}" method="post">
				<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
				<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username: </label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>
				
				<div class="mb-3">
					<label for="password">Password: </label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Login">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

<!-- {% if is_user_authenticated == False %}
	<h1>Something went Wrong</h1>
	<p>Please contact your administrator or reset your password</p>
	<a href="{% url 'todolist:index' %}">Back to index page</a>

{% endif %} -->

todolist/templates/todolist/register.html
{% if is_user_registered == False %}
	<h1>Duplicate User Found!</h1>
	<p>A duplicate user has been found, user creation unsccessful</p>
{% else %}
	<h1>User Successfully Created!</h1>
	<p>The account for  {{first_name}} {{last_name}} has been successfully created</p>

{% endif %}

todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{task_name}}</h1>
	<h3>Description</h3>
	<p>{{description}}</p>
	<h3>Status</h3>
	<p>{{status}}</p>

	<button class="btn btn-primary mx-1 text-decoration-none"><a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
	</button>

	<button class="btn btn-danger mx-1 text-decoration-none"><a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
	</button>

	<button class="btn btn-warning mx-1 text-decoration-none"><a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
	</button>

</div>

{% endblock %}

todolist/templates/todolist/update_event.html
{% extends 'base.html' %}

{% block title %}Update Event{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Event</h1>
				{% if error == True %}
					<p class="text-danger">Event not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_event' event_id %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="event_name">Event Name: </label>
					<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
				</div>
				
				<div class="mb-3">
					<label for="Description">Description: </label>
					<textarea class="form-control" name="Description" value="{{ Description }}" required></textarea>
				</div>

				<div class="mb-3">
					<label for="status">Status: </label>
					<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
				</div>
			

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Update Event">
				</div>
				
			</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">Task not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
				</div>
				
				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" name="description" value="{{ description }}" required></textarea>
				</div>

				<div class="mb-3">
					<label for="status">Status: </label>
					<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
				</div>
			

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Update Task">
				</div>
				
			</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}